// <auto-generated />
using System;
using Cadastro.Cliente.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cadastro.Cliente.Infra.Data.Migrations
{
    [DbContext(typeof(CadastroClienteDbContext))]
    partial class CadastroClienteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Cadastro.Cliente.Domain.Clientes.ClienteCrmall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDeNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<short>("Sexo")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.ToTable("ClienteCrmall", "ProjetoCliente");
                });

            modelBuilder.Entity("Cadastro.Cliente.Domain.Clientes.EnderecoCrMall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Localidade")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<short>("Numero")
                        .HasMaxLength(200)
                        .HasColumnType("smallint");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.ToTable("EnderecoCrmall", "ProjetoCliente");
                });

            modelBuilder.Entity("Cadastro.Cliente.Domain.Clientes.ClienteCrmall", b =>
                {
                    b.HasOne("Cadastro.Cliente.Domain.Clientes.EnderecoCrMall", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });
#pragma warning restore 612, 618
        }
    }
}
